---
kind: Service
apiVersion: v1
metadata:
  name: guestbook
  labels:
    app: guestbook
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  ports:
  - port: 3000
    targetPort: http-server
  selector:
    app: guestbook
  type: LoadBalancer
